site_name: LyoPRONTO Documentation

theme:
    name: "material"

plugins:
    - mkdocstrings:
        default_handler: python
    - mike:
        version_selector: true
        canonical_version: latest
    - ipynb
extra:
    version:
        provider: mike

nav:
    # List of web pages to show, in order
    - index.md
    - tutorials.md
    - how-to-guides.md
        - ex_knownRp_PD.py
    - explanation.md
    - reference.md

